#
# Copyright 2018 IBM All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'


volumes:
  orderer.cartracker.com:
  peer0.manufacturerorg.cartracker.com:
  peer0.dealershiporg.cartracker.com:
  peer0.insuranceorg.cartracker.com:
  peer0.carregistrationauthorityorg.cartracker.com:
  peer0.buyerorg.cartracker.com:
  
networks:
  mainnet:

services:
  manufacturerorg-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-manufacturerorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manufacturerorg.cartracker.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ManufacturerOrg_CA_PRIVATE_KEY
    ports:
    - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.manufacturerorg.cartracker.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ManufacturerOrg_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/manufacturerorg.cartracker.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerManufacturerOrg
    networks:
    - mainnet

  peer0.manufacturerorg.cartracker.com:
    container_name: peer0.manufacturerorg.cartracker.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.manufacturerorg.cartracker.com
    networks:
      - mainnet

  dealershiporg-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-dealershiporg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dealershiporg.cartracker.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/DealershipOrg_CA_PRIVATE_KEY
    ports:
    - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dealershiporg.cartracker.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/DealershipOrg_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/dealershiporg.cartracker.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerDealershipOrg
    networks:
    - mainnet

  peer0.dealershiporg.cartracker.com:
    container_name: peer0.dealershiporg.cartracker.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.dealershiporg.cartracker.com
    networks:
      - mainnet

  insuranceorg-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insuranceorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insuranceorg.cartracker.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/InsuranceOrg_CA_PRIVATE_KEY
    ports:
    - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.insuranceorg.cartracker.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/InsuranceOrg_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/insuranceorg.cartracker.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerInsuranceOrg
    networks:
    - mainnet

  peer0.insuranceorg.cartracker.com:
    container_name: peer0.insuranceorg.cartracker.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.insuranceorg.cartracker.com
    networks:
      - mainnet

  carregistrationauthorityorg-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-carregistrationauthorityorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.carregistrationauthorityorg.cartracker.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CarRegistrationAuthorityOrg_CA_PRIVATE_KEY
    ports:
    - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.carregistrationauthorityorg.cartracker.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CarRegistrationAuthorityOrg_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/carregistrationauthorityorg.cartracker.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCarRegistrationAuthorityOrg
    networks:
    - mainnet

  peer0.carregistrationauthorityorg.cartracker.com:
    container_name: peer0.carregistrationauthorityorg.cartracker.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.carregistrationauthorityorg.cartracker.com
    networks:
      - mainnet

  buyerorg-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-buyerorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.buyerorg.cartracker.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/BuyerOrg_CA_PRIVATE_KEY
    ports:
    - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.buyerorg.cartracker.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/BuyerOrg_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
    - ./crypto-config/peerOrganizations/buyerorg.cartracker.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerBuyerOrg
    networks:
    - mainnet

  peer0.buyerorg.cartracker.com:
    container_name: peer0.buyerorg.cartracker.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.buyerorg.cartracker.com
    networks:
      - mainnet

  orderer.cartracker.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.cartracker.com
    container_name: orderer.cartracker.com
    networks:
      - mainnet


